name: update demo

on:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - uses: charmbracelet/vhs-action@v1
        with:
          path: ./tapes/demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: go install github.com/charmbracelet/vhs@latest
      - name: update gif
        run: |
          for t in ./tapes/*; do
            vhs < $t
          done

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update demo
          body: ${{ github.sha }}
          branch: docs/update-demo
          branch-suffix: short-commit-hash
